include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Eskimiş komut uyarılarını (groupValue, onChanged vb.) tamamen gizler
    deprecated_member_use: ignore
    # Gereksiz kütüphane import uyarılarını gizler
    unused_import: ignore

linter:
  rules:
    # Tek satırlık if bloklarında süslü parantez zorunluluğunu kaldırır
    curly_braces_in_flow_control_structures: false
    # Print komutu kullanıldığında çıkan uyarıyı kapatır
    avoid_print: false
    # Const kullanmadığında çıkan mavi uyarıları azaltır
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false